// Generated by CoffeeScript 1.6.2
(function() {
  var NSI;

  NSI = (function() {
    NSI.prototype.opts = {};

    function NSI(options) {
      this.options = options;
      this.options = $.extend({}, this.opts, this.options);
      $("ul.nav li.dropdown").hover((function() {
        return $(this).addClass("open");
      }), function() {
        return $(this).removeClass("open");
      });
    }

    NSI.prototype.initFlexslider = function() {
      return $(".flexslider").flexslider({
        namespace: "flex-",
        selector: ".slides > li",
        animation: "fade",
        easing: "swing",
        direction: "horizontal",
        reverse: false,
        animationLoop: true,
        smoothHeight: false,
        startAt: 0,
        slideshow: true,
        slideshowSpeed: 7000,
        animationSpeed: 600,
        initDelay: 0,
        randomize: false,
        pauseOnAction: true,
        pauseOnHover: false,
        useCSS: true,
        touch: true,
        video: false,
        controlNav: true,
        directionNav: true,
        prevText: "Previous",
        nextText: "Next",
        keyboard: true,
        multipleKeyboard: false,
        mousewheel: false,
        pausePlay: false,
        pauseText: 'Pause',
        playText: 'Play',
        controlsContainer: "",
        manualControls: "",
        sync: "",
        asNavFor: "",
        itemWidth: 0,
        itemMargin: 0,
        minItems: 0,
        maxItems: 0,
        move: 0,
        start: function() {},
        before: function() {},
        after: function() {},
        end: function() {},
        added: function() {},
        removed: function() {}
      });
    };

    return NSI;

  })();

  window.NSI = NSI || {};

}).call(this);
